apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rhtap-install
spec:
  params:
    - name: test-id
      type: string
    - name: test-name
      type: string
    - name: ocp-login-command
      type: string
      description: ""
  steps:
    - name: install
      image: quay.io/konflux-qe-incubator/konflux-qe-tools@sha256:ad94717d69e5d192a92b0b9b6cda4223940303f4ff297ea2b69e7cddb94ff7d5
      env:
        - name: TEST_ID
          value: $(params.test-id)
        - name: TEST_NAME
          value: $(params.test-name)
        - name: RHTAP_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: rhtap-installer-configuration
              key: config.env
      script: |
        #!/bin/sh
        $(params.ocp-login-command)
        oc whoami

        git clone -b release-1.0.1 https://github.com/redhat-appstudio/rhtap-installer.git

        cd rhtap-installer

        echo "$RHTAP_CONFIGURATION" > config.sh
        chmod +x config.sh
        source ./config.sh

        ./bin/make.sh values
        ./bin/make.sh apply -n rhtap -- --debug --values private-values.yaml

        echo -e "INFO: RHTAP was installed successfully:"

        oc get po -n rhtap
